### ISSUE TITLE
Updates for business cards

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jb-business-cards#2]
- Sentence case each Word in company title
- Try smaller point size for letters 2....

- left aligned 
- Company name 
- Email
- Phone
- Picture on rear

**Comment by iandstanley** [comment]
@jenniferbrickwell how about this text in the logo?

![logo-with-tagline](https://cloud.githubusercontent.com/assets/6939289/18958651/3be98d42-865b-11e6-82f7-8671f60640bd.png)

**Comment by iandstanley** [comment]
Take a look at this PDF

ORIGINAL IDEA ...
first and last pages was were I was looking at a double sided 

- issues with this are that the logo and left justified text don't look right (as I originally mentioned because (1) the image is irregular and needs to be justified (2) the image looks really odd if you push it to one side (3) image too small if you put in on one half 

FIRST ALTERNATE IDEA
I played around with a portrait version but that leaves too much white space on the card so rejected that quickly

Then I played around with the idea that you had of having your picture on the rear and came up with the third page which I think works very well (even though it wasn't one of our original )....

PROPOSAL 
- front facing as per  the third page of this PDF
- rear facing to have logo and company name as per logo above (as per comment an hour ago including text and tagline in landscape format)

@jenniferbrickwell  What do you think?




[jb-business-card.pdf](https://github.com/stereocats/jb-business-cards/files/501066/jb-business-card.pdf)

**Comment by jenniferbrickwell** [comment]
Thanks for this Ian. Good first draft. First comments:

- Picture on back is excellent- with or without contact information. Great. Probably impossible but can we rotate the picture to be landscape so I can see it?
- Front- can you put Tel: next to the telephone number and reduce the size of the font for the telephone number so it is the same size as the email. Please add the website in the same size font. Happy for the image to be reduced in size to fit this info on. Just would like this section to look neat.
- Capital L for ltd please.
Let's see how this looks and will pray about it. Could fill white space on portrait card with key words- eg organise, plan, execute, deliver but need to pray about this.

**Comment by jenniferbrickwell** [comment]
Hi sorry for the delay with this. This looks good. Can we get a version with italics just to compare?

**Comment by iandstanley** [comment]
Impossible to rotate a portrait close up photo to landscape and still have a reasonable cropping

**Comment by iandstanley** [comment]
with italics for comparison
![logo-with-tagline](https://cloud.githubusercontent.com/assets/6939289/19012567/9bd35452-87b1-11e6-8594-ddf91b1e3184.png)

**Comment by iandstanley** [comment]
see latest commits today
